spring:
  profiles:
    active: db, core, admin, wx
  messages:
    encoding: UTF-8

server:
  port: 443
  ssl.key-store: classpath:3234611_www.bj-rklk.com.pfx
  ssl.key-store-password: 96wcRO3G
  ssl.keyStoreType: PKCS12
  tomcat:
    max-connections: 50000

logging:
  config: classpath:logback-spring.xml